resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: master
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - '/Activities/Credentials/*'
    - '/Activities/Activities.Credentials.sln'

# variables:
#   - template: vars.yml
#   - template: "../.pipelines/variables/vars.yml"

pr:
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - '/Activities/Credentials/*'
    - '/Activities/Activities.Credentials.sln'

# jobs:
#   - template: "../.pipelines/jobs/ci.yml"
#     parameters:
#       BuildProject: "../Activities.Credentials.sln"
#       BuildConfiguration: "Release"
#       BuildPlatform: "AnyCPU"
#       rootPath: $(Build.SourcesDirectory)\Activities\Credentials\
#       packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
#       versionReference: "UiPath.Credentials.Activities/Properties/AssemblyInfo.cs"
#       versionNumber: ${{ variables.versionNumber }}
#       versionSuffix: ${{ variables.versionSuffix }}

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Credentials'
      solutionPath: '../Activities.Credentials.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sdkBuild: false
      enableCDStages: false
